### ISSUE TITLE
Integrate current-location

### ISSUE THREAD

**Issue by zeke** [Jam3/extract-streetview#1]
@maxogden just published the https://github.com/maxogden/current-location package recently:

```
❯ npm i -g current-location && current-location
{"latitude":29.948705,"longitude":-90.133073}
```

It would be cool if this CLI used that in the absence of a `lat,lng` argument.

**Comment by mattdesl** [comment]
:+1: Neat idea. Can also use `navigator.geolocation` to get the current location since we are already using the browser here.

**Comment by mattdesl** [comment]
Now in `1.1.0` you can do this:

``` sh
extract-streetview current > image.png
```

**Comment by zeke** [comment]
:clap:
